host_url:
  type: string
  default: ''
  description: Host URL without http:// or https://
website_id:
  type: string
  default: ''
user_id_tracking:
  type: string
  default: ''
  description: Enter a field name on the current user object such as id, username or external_id.
subdomain_tracking:
  type: bool
  default: false
  description: Track visitors across main domain & subdomains, assuming discourse is on a subdomain.
