host_url:
  type: string
  default: ''
  description: Host URL without http:// or https://
website_id:
  type: string
  default: ''
exclude_groups:
  type: string
  default: ''
  description: Comma separated list of groups to exclude from tracking such as admins, staff.
user_id_tracking:
  type: string
  default: ''
  description: An indentifying field name on the current user object such as id, username or external_id.
subdomain_tracking:
  type: bool
  default: false
  description: Track visitors across main domain & subdomains, assuming discourse is on a subdomain.
do_not_track:
  type: bool
  default: true
  description: So tracking requests will not be sent if visitors do not wish to be tracked
tracking_cookies:
  type: bool
  default: true
  description: Disables all first party cookies. Existing Matomo cookies for this website will be deleted on the next pageview.
