host_url:
  type: string
  default: ''
  description: Host URL without http:// or https://
website_id:
  type: string
  default: ''
subdomain_tracking:
  type: bool
  default: false
  description: Track across domain & subdomains, assuming discourse is subdomain.
