host_url:
  type: string
  default: ''
  description: Host URL without http:// or https://
website_id:
  type: string
  default: ''
crossdomain_tracking:
  type: bool
  default: false
  description: Track visitors across site domain and subdomains
