host_url:
  type: string
  default: ''
  description: Host URL without http:// or https://
website_id:
  type: string
  default: ''
track_subdomains:
  type: bool
  default: false
  description: Track visitors across all subdomains
